name: Publish to TER

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  publish:
    name: Publish release to TER
    runs-on: ubuntu-latest

    env:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        shell: bash
        run: echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Get TER upload comment
        shell: bash
        run: |
          comment="$(git tag -l "$version" --format='%(contents)')"

          if [[ -z "${comment// }" ]]; then
            comment="Released version $version"
          fi

          {
            echo 'comment<<EOF'
            echo "$comment"
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2

      - name: Install Tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-interaction

      - name: Publish to TER
        run: php ~/.composer/vendor/bin/tailor ter:publish --comment "${{ env.comment }}" "${{ env.version }}"
